#!/usr/bin/env python3
"""Generate src/data/europe-outline.ts: an approximate SVG outline of Europe.

Source: Natural Earth 1:50m land polygons (public domain), e.g.
https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_50m_land.geojson

Usage: python3 scripts/europe-map.py ne_50m_land.geojson > src/data/europe-outline.ts

The projection (equirectangular, scaled by cos of the central latitude) is
written to the output too, so the talks map places its markers with exactly
the same formula (see src/components/EuropeMap.astro).
"""
import json
import math
import sys

LON_MIN, LON_MAX = -10.0, 20.0
LAT_MIN, LAT_MAX = 35.5, 51.0
WIDTH = 800
COS = math.cos(math.radians((LAT_MIN + LAT_MAX) / 2))
K = WIDTH / ((LON_MAX - LON_MIN) * COS)
HEIGHT = round((LAT_MAX - LAT_MIN) * K)
PAD = 25  # clip outside the visible box so artificial clip edges stay hidden
TOLERANCE = 0.7  # Douglas–Peucker tolerance, in SVG units


def project(lon, lat):
    return ((lon - LON_MIN) * COS * K, (LAT_MAX - lat) * K)


def clip(poly, xmin, ymin, xmax, ymax):
    """Sutherland–Hodgman clipping of a closed polygon against a rectangle."""
    edges = [
        (lambda p: p[0] >= xmin, lambda a, b: (xmin, a[1] + (b[1] - a[1]) * (xmin - a[0]) / (b[0] - a[0]))),
        (lambda p: p[0] <= xmax, lambda a, b: (xmax, a[1] + (b[1] - a[1]) * (xmax - a[0]) / (b[0] - a[0]))),
        (lambda p: p[1] >= ymin, lambda a, b: (a[0] + (b[0] - a[0]) * (ymin - a[1]) / (b[1] - a[1]), ymin)),
        (lambda p: p[1] <= ymax, lambda a, b: (a[0] + (b[0] - a[0]) * (ymax - a[1]) / (b[1] - a[1]), ymax)),
    ]
    for inside, cut in edges:
        if not poly:
            break
        out = []
        prev = poly[-1]
        for cur in poly:
            if inside(cur):
                if not inside(prev):
                    out.append(cut(prev, cur))
                out.append(cur)
            elif inside(prev):
                out.append(cut(prev, cur))
            prev = cur
        poly = out
    return poly


def simplify(points, tol):
    """Douglas–Peucker on an open polyline."""
    if len(points) < 3:
        return points
    (x1, y1), (x2, y2) = points[0], points[-1]
    dx, dy = x2 - x1, y2 - y1
    norm = math.hypot(dx, dy) or 1e-9
    best, index = 0.0, 0
    for i in range(1, len(points) - 1):
        px, py = points[i]
        d = abs(dy * px - dx * py + x2 * y1 - y2 * x1) / norm
        if d > best:
            best, index = d, i
    if best <= tol:
        return [points[0], points[-1]]
    return simplify(points[: index + 1], tol)[:-1] + simplify(points[index:], tol)


def main(path):
    with open(path) as f:
        land = json.load(f)
    parts = []
    for feature in land["features"]:
        geom = feature["geometry"]
        polygons = geom["coordinates"] if geom["type"] == "MultiPolygon" else [geom["coordinates"]]
        for polygon in polygons:
            ring = polygon[0]  # outer ring only: lakes are not needed at this scale
            pts = [project(lon, lat) for lon, lat in ring]
            pts = clip(pts, -PAD, -PAD, WIDTH + PAD, HEIGHT + PAD)
            if len(pts) < 3:
                continue
            # Split the closed ring at its farthest point from the start, so
            # Douglas–Peucker never sees a zero-length chord.
            far = max(range(len(pts)), key=lambda i: math.dist(pts[0], pts[i]))
            pts = simplify(pts[: far + 1], TOLERANCE)[:-1] + simplify(pts[far:] + [pts[0]], TOLERANCE)[:-1]
            if len(pts) < 3:
                continue
            xs, ys = [p[0] for p in pts], [p[1] for p in pts]
            if (max(xs) - min(xs)) * (max(ys) - min(ys)) < 4:  # drop specks
                continue
            d = "M" + "L".join(f"{x:.1f},{y:.1f}" for x, y in pts) + "Z"
            parts.append(d)
    print("// Generated by scripts/europe-map.py from Natural Earth 1:50m land (public domain).")
    print("// Do not edit by hand.")
    print(
        "export const EUROPE = "
        + json.dumps(
            {
                "width": WIDTH,
                "height": HEIGHT,
                "lonMin": LON_MIN,
                "latMax": LAT_MAX,
                "cos": round(COS, 6),
                "k": round(K, 6),
                "path": "".join(parts),
            }
        )
        + " as const;"
    )


if __name__ == "__main__":
    main(sys.argv[1])
